### PR TITLE
extract a generic vif function

### PR DESCRIPTION
**Pull request by soumyaray**
DO NOT MERGE YET

Refactoring VIF code

### CODE REVIEW

**Comment by soumyaray** [comment]
@NicholasDanks I'm thinking to extract the new utility functions I created in `R/evaluation.R` to new files:

```
items_of_construct() —> R/model_extractions.R
antecedents_of_construct() —> R/model_extractions.R

compute_vif() —> R_metrics.R
```

What do you think?

**Comment by NicholasDanks** [comment]
Looks good. TBH, we should probably go through all the files in R/ and check if the methods are in the correct files. and whether there is duplication or repetition across the files and methods.

**Comment by soumyaray** [comment]
Ok — I'll leave comments on top of each of the new files regarding the PURPOSE of the file. We can move other functions around as we later need.

**Comment by soumyaray** [comment]
@NicholasDanks if OSX test pass on TravisCI, this is ready to merge into `develop`

**Pull request merged**
